# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Gradle Package


on:
  push:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Commit
        uses: actions/checkout@v4

      - name: Setup java environment
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Assemble APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease

      - name: Prepare Keystore
        run: |
          echo "${{ secrets.KEY_STORE }}" | base64 --decode > app/build/outputs/apk/release/signingKey.jks

      - name: Align APK (Optional but recommended)
        run: |
          zipalign -v -p 4 app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk

      - name: Sign APK
        run: |
          /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner sign --ks app/build/outputs/apk/release/signingKey.jks --ks-key-alias ${{ secrets.KEY_ALIAS }} --ks-pass pass:${{ secrets.KEY_STORE_PASSWORD }} --key-pass pass:${{ secrets.KEY_PASSWORD }} --out app/build/outputs/apk/release/app-release-signed.apk app/build/outputs/apk/release/app-release-unsigned-aligned.apk

      - name: Verify APK Signature
        run: |
          /usr/local/lib/android/sdk/build-tools/34.0.0/apksigner verify app/build/outputs/apk/release/app-release-signed.apk

      - name: Deploy to Google Play (if applicable)
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.rtbishop.look4sat
          releaseFiles: app/build/outputs/apk/release/app-release-signed.apk
          track: production
          whatsNewDirectory: fastlane/metadata/android/en-US/whatsnew

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/build/outputs/apk/release/app-release-signed.apk"
          bodyFile: fastlane/metadata/android/en-US/whatsnew/whatsnew-en-US
          token: ${{ secrets.RELEASE_TOKEN }}

        TOKEN: ${{ secrets.GITHUB_TOKEN }}

          artifacts: "app/build/outputs/apk/release/look4sat.apk,app/build/outputs/apk/release/look4sat.aab"
          bodyFile: fastlane/metadata/android/en-US/whatsnew/whatsnew-en-US
          token: ${{ secrets.RELEASE_TOKEN }}
